version: '3'
services:

  ### Database postgres 'db_hibernate'
  db-hibernate:
    container_name: db_hibernate
    image: postgres:latest
    environment:
      POSTGRES_DB: db_hibernate
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432
    volumes:
      - db_hibernate_data:/var/lib/postgresql/data


volumes:
  db_hibernate_data:
